# Sales Performance Analysis
## Introduction
This project presents a comprehensive analysis of the sales performance of a retail store. 
By examining sales data, we aim to identify key insights into top-selling products, regional performance, and monthly sales trends.
The analysis will be visualized through an interactive Power BI dashboard, providing a clear and engaging way to interpret the data,
enabling insights into the divers of revenue and high-demand products.

## Data Source
The primary source of Data used here is the Sales Data provided by the Store.

## Data Fields

Region: The geographic region where the store is located.
Market: The specific market or city where the store operates.
Total revenue: The total revenue generated by the sale, typically calculated by multiplying the quantity sold by the unit price.
Units Price: Refers to the cost per single unit of a product 
Customer ID: Customer ID is a unique identifier assigned to each customer in a database or sales system. 
Order ID is a unique identifier assigned to each purchase or transaction made by a customer.

## Basic statistics about the dataset:
- Total Sales: #345,000
- Total Revenue: #10,587,500
- Number of Region:4
- Total Number of Items:6
- The dataset spans from 2023-2024

## Methodology
Data Preparation: I ensured the sales data was clean and structured, with columns for product, region, month, and sales figures.

- Creating the Pivot Table:

In Excel, I selected the range of my data and then inserted a pivot table.
I set the rows to include Product and Region, and the columns to reflect Month.

![Cap Rp](https://github.com/user-attachments/assets/33c54c7b-f002-422d-9728-174b7ade69c6)

I used the Values area to summarize Total Sales, applying the sum function to aggregate sales figures.

Analyzing the Results: The pivot table provided a clear summary of total sales by product, region, and month. 

![cap Ts](https://github.com/user-attachments/assets/efb4ced9-130f-46b4-b31c-148715c91734)

![Cap Rs](https://github.com/user-attachments/assets/3bb3d02a-d1aa-4a5d-9d11-7fe2320be1e9)

![Cap Rm](https://github.com/user-attachments/assets/131fce15-0b98-457e-ac1b-d38787a40be4)

For example, I could quickly see how much each product sold in different regions across various months, which helped identify trends and performance metrics.

## Metrics Calculated

### Average Sales per Product
- **Shirt**: =AVERAGEIF(C:C,C2,H:H)
- **Shoes**: =AVERAGEIF(C:C,C3,H:H)
- **Hat**: =AVERAGEIF(C:C,C4,H:H)
- **Socks**: =AVERAGEIF(C:C,C5,H:H)
- **Jacket**: =AVERAGEIF(C:C,C6,H:H)
- **Gloves**: =AVERAGEIF(C:C,C7,H:H)

### Total Revenue by Region
- **North Region**: = SUMIF(D:D,D2,H:H)
- **South Region**: = SUMIF(D:D,D3,H:H)
- **East Region**: = SUMIF(D:D,D4,H:H)
- **West Region**: = SUMIF(D:D,D5,H:H)

## Results
- Average Sales for Shirt: 326.6666667
- Average Sales fo Shoes: 308.75
- Average Sales for Hat: 158.75
- Average Sales for Socks: 121.6666667
- Average Sales for Jacket: 140
- Average Sales for Gloves: 200

- Total Revenue for North Region: 1950000
- Total Revenue for South Region: 4675000
- Total Revenue for East Region: 2450000
- Total Revenue for West Region: 1512500



## Total Quantity Sold Analysis

### SQL Query
The following SQL query was used to calculate the total quantity sold for each product in the dataset:


### Result
![Cap sql p](https://github.com/user-attachments/assets/cab34651-79c4-4e8b-a18a-7f8bc0c4111c)

This query aggregates the sales data to provide the total quantity sold for each product.
By grouping the results by product name, we can see how many units were sold for each item.

### Results Interpretation
The output displays each product along with its total quantity sold, offering valuable insights into:

-  Sales Performance: Identifying which products are most popular in terms of quantity sold.
-  Inventory Management: Assisting in stock planning to meet demand for high-selling products.
-  Trend Analysis: Facilitating comparison of sales trends over time for informed decision-making.

## Highest Selling Product Analysis

### SQL Query
The following SQL query was used to determine the highest revenue-generating products in the dataset:

SELECT product, MAX(Total_Revenue) AS highest_selling_product
FROM [dbo].[LITA Capstone Dataset5]
GROUP BY product;

### Result
![Cap sql m](https://github.com/user-attachments/assets/6a496148-a5b3-43e0-8205-963031f948f9)

This query groups the sales data by product and retrieves the maximum total revenue for each product.
The output provides insights into which products are performing best in terms of sales.

#### Results Interpretation
The results indicate the highest revenue-generating products, which can help in:

-  Identifying top performers in the market.
-  Informing strategic business decisions regarding inventory and marketing.
-  Comparing product performance over time to assess trends.

## Sales Dashboard
This sales dashboard provides a visual representation of key sales metrics, allowing for quick insights into
sales performance across various dimensions such as products, regions, and time periods. 


### Tools Used
- **Visualization Software**:  Power BI 
- **Data Source**: Capstone Sales Data
  
![Sales-DB](https://github.com/user-attachments/assets/3644762e-4b9e-4380-9e81-4c4906e9c87a)

### Total Revenue by Product Visualization

The visualization of total revenue by product provides a clear and concise view of how different products contribute to overall revenue. 
This analysis helps sellers understand which products are performing well and which may need additional focus or support.

Visualization Type
The total revenue by product is presented using cluster column chart. 
This type of chart is effective for comparing the revenue generated by each product, making it easy to identify top performers at a glance.

![Cap  R by P](https://github.com/user-attachments/assets/bcb6e5f1-819c-4f34-89b5-695f3fddc22b)

### **Explanation of the Chart** 
X-Axis: Represents the different products available in the dataset.

Y-Axis: Represents the total revenue generated by each product.

Bars: Each bar corresponds to a product, with the height indicating the total revenue. 
Taller bars signify higher revenue, while shorter bars indicate lower revenue.

 ### **Insights**
 
From the total revenue visualization, several key insights can be derived:
-  Top Performers: Identify which products generate the most revenue. These are likely your best-selling items and should be prioritized in marketing and inventory management.
-  Underperforming Products: Products with low revenue can be analyzed further to understand why they are not performing as expected.
   This may lead to decisions regarding promotions, pricing strategies, or even product discontinuation.
-  Revenue Trends: By comparing this chart to historical data, one can assess how product revenue has changed over time, providing insights into market trends and consumer preferences.

### Region by Total Sales

This visualization allows business owners to quickly compare sales performance across different regions.
It helps identify which regions are performing well and which may need attention.

Visualization Type
The region by total sales is presented using Stacked column chart.
The chart can highlight high-performing regions that might be leveraged for expansion or low-performing regions that may require targeted interventions.

![Cap R by s](https://github.com/user-attachments/assets/11ed4b62-8232-4154-ae3c-6a2f51b6c365)

### **Explanation of the Chart** 
X-Axis: Represents the quantity of goods sold available in the dataset.

Y-Axis: Represents the sum of total revenue generated by each product.
Legend: Represents the various region of customers.

Each segment in the stacked columns represents a specific product, 
showing how much revenue each contributes to the total sales. This helps in understanding which products drive revenue and which do not.

 ### **Insights** 
From the to visualization, several key insights can be derived:
-  A retail business analysis using a stacked column chart to display total revenue, quantity sold by region, 
it will help to understand which region are performing best.

-  By leveraging a stacked column chart to represent quantity by total revenue, 
businesses can gain valuable insights into their sales dynamics, improve decision-making, and ultimately drive better performance.


### Monthly and Yearly Sales Trend

This visualization clearly illustrate trends in sales data, making it easy to identify patterns over time, such as seasonal fluctuations or overall growth.

Visualization Type
The Monthly and Yearly Sales Trend is presented using line chart.
Line chart compareed different time periods months, helping to assess performance and spot significant changes or anomalies.
![Cap  line chart](https://github.com/user-attachments/assets/62893b6f-76be-4289-9b9d-40d74eecfb92)

### **Explanation of the Chart** 
X-Axis: Represents Products, Order date(Month & yearly)  in the dataset.

Y-Axis: Represents the sum of total revenue generated monthly & yearly.

 Comparing yearly sales trends allows businesses to assess growth or decline relative to previous years,
 providing context for current performance.

 ### **Insights** 
From the to visualization, several key insights can be derived:

 -  Monthly sales data reveals seasonal trends, helping businesses understand when sales peak or dip
 -  Using a line chart to represent monthly and yearly trends by total sales provides a clear and effective way to analyze sales performance over time.
 -  It enables businesses to identify trends, forecast future sales, and make data-driven decisions, ultimately enhancing their strategic planning efforts.


### Top Performing Product

This visualization clearly illustrate top performing product.

Visualization Type
 A donut chart effectively shows the percentage of total sales or revenue contributed by each top-performing product, 
 making it easy to see which products dominate sales.
 
 ![Cap donut](https://github.com/user-attachments/assets/a4e81fd9-5d1a-46ff-8787-f63970a54440)

 ### **Explanation of the Chart** 
 
Legend: Represents Products in the dataset.

Values: Represents the Maximum of total revenue.

By limiting the chart to the top-performing products, one can  draw attention to those that are significantly contributing to overall performance, 
making it easier for business owner to recognize and analyze these key items.

 ### **Insights** 
From the to visualization, donut charts are visually engaging and straightforward, 
making it easy for audiences to grasp the data without needing to interpret complex numerical figures.


###Summary

In this report, I explored  sales data, uncover key insights such as top-selling products, regional 
performance, and monthly sales trends. I extracted my data from excel, summarized the data with pivot table,
then createed visuals, making it easier to present and understand key insight.

## Conclusion

  By utilizing charts such as stacked column charts, line charts, and donut charts, we gained valuable insights into regional sales performance, monthly and yearly trends, and the contributions of top-performing products.

These visualizations not only enhance our understanding of sales dynamics but also facilitate data-driven decision-making. They provide clarity and ease of interpretation for business owners, allowing for informed strategies and improved business outcomes.

The ability to visualize complex data in a straightforward manner is crucial for effective communication and analysis in today’s data-centric environment. By implementing these visualizations, organizations can identify opportunities for growth, assess performance, and make strategic adjustments as needed.

For further exploration, the provided datasets and code in this repository can serve as a foundation for continued analysis and refinement of sales strategies.

This process allowed for efficient data exploration and summary, helping to derive actionable insights from the sales data.






